config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  scope "/admin" do
    resources :users, except: [ :show ]
  end

  get 'upload' => 'delivery_loader#index'
  post 'upload' => 'delivery_loader#upload'

  get 'locations' => 'locations#index'
  get 'location/latest' => 'locations#latest'
  post 'location/update' => 'locations#update'

  resources :deliveries, only: [ :index, :update ]

  get 'deliveries/calc' => 'deliveries#calc'
  get 'deliveries/user/:id' => 'deliveries#user'

  resources :customers, only: [ :index, :show, :edit, :destroy, :update ]

end

app/models/customer.rb
require 'post_code_finder'

class Customer < ActiveRecord::Base
  has_many :deliveries

  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :postcode, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  # On updating a record check the postcode and roadway coords in case they
  # have changed
  before_validation(on: :update) do
    # get the postcode coords for this record
    coords = PostCodeFinder.get(postcode)
    if coords.nil?
      # nothing found for this code, will be flagged to user
      self.latitude = 0
      self.longitude = 0
    else
      # find nearest point to the postcode that is on a road
      nrp = PostCodeFinder.nearest_road_point(
        {lat: coords[:lat], lon: coords[:lon]})
      if nrp.nil?
        # no nearest road found
        self.latitude = 0
        self.longitude = 0
      else
        self.latitude = nrp[:lat]
        self.longitude = nrp[:lon]
      end
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :require_admin
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  def index
    # check if any customer records have (0,0) coords => invalid,
    # flash an alert and these records will be marked in view too.
    if Customer.find_by(latitude: 0, longitude: 0)
      # order by latitude so invalid are at top
      @customers = Customer.order(:latitude)
      flash[:alert] = "Some customer records have invalid GPS location information." +
        "They need to be edited manually and are highlighted in red below"
    else
      @customers = Customer.all.order(:name)
    end
  end

  # GET /customers/1/edit
  def edit
  end

  # GET /customers/1
  def show
    @deliveries = Delivery.where(customer_id: @customer.id).order(date: :desc);
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to customers_path, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:code, :name, :address, :postcode, :latitude, :longitude)
    end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit "Update", class: "button alert" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="small-12 large-5 small-centered columns">

    <h3 class="form-title">Edit Customer Details</h3>

    <%= render 'form' %>

  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="small-12 small-centered columns">

<h3 class="form-title">Customers</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postcode</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <% if customer.latitude == 0 %>
        <tr class="problem-row">
      <% else %>
        <tr>
      <% end %>
          <td><%= link_to customer.name, customer_path(customer) %></td>
          <td><%= customer.address %></td>
          <td><%= customer.postcode %></td>
          <td><%= link_to 'Edit', edit_customer_path(customer), class: "button tiny" %></td>
          <td><%= link_to 'Delete', customer, method: :delete,
            data: { confirm: 'Are you sure?' }, class: "button tiny alert" %></td>
        </tr>      
    <% end %>
  </tbody>
</table>

</div>
</div>

app/views/customers/show.html.erb
<div id="customer-deliveries" class="row">
  <div class="small-12 large-10 small-centered columns">

    <div class="row page-head">
      <div class="small-7 columns">
        <h3><%= @customer.name %></h3>
      </div>
    </div>

    <div id="customer-details">
      <%= @customer.address %> <%= @customer.postcode %>
    </div>

    <!-- table header -->
    <div class="row table-head">
      <div class="small-3 columns">Scheduled</div>
      <div class="small-6 columns">Driver</div>
      <div class="small-3 columns end">Delivered</div>
    </div>

    <div id="delivery-list">
    <% @deliveries.each do |d| %>
      <div class="row <%= cycle('odd', 'even') -%>">
        <div class="small-3 columns">
          <%= d.date.strftime("%d-%m-%Y") %>
        </div>
        <div class="small-6 columns">
          <%= d.user.email %>
        </div>
        <div class="small-3 columns">
          <% if d.complete.nil? %>
            Pending
          <% else %>
            <%= d.complete.strftime("%d/%m %H:%M") %>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>

  </div>
</div>