config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  scope "/admin" do
    resources :users, except: [ :show ]
  end

  get 'upload' => 'delivery_loader#index'
  post 'upload' => 'delivery_loader#upload'

  get 'locations' => 'locations#index'
  get 'location/latest' => 'locations#latest'
  post 'location/update' => 'locations#update'

  resources :deliveries, only: [ :index, :update ]

  get 'deliveries/calc' => 'deliveries#calc'
  get 'deliveries/user/:id' => 'deliveries#user'

  resources :customers, only: [ :index, :show, :edit, :destroy, :update ]

end

app/views/layouts/_deliveries.html.erb
 <% @deliveries.each do |delivery| %>
      <div class="row">
        <div class="cell-head">
          <%# Alter content depending on the status of the delivery %>
          <div class="small-4 columns">
            <%# if delivery is complete show time %>
            <% if !delivery.complete.nil? %>
               <%= delivery.complete.strftime("%H:%M") %>
            <%# otherwise show precedence is known %>
            <% elsif !delivery.precedence.nil? %>
              <%= delivery.precedence %>
            <% end %> 
          </div>

          <div class="small-8 columns complete">
            <% if !current_user.admin %>
              <%# Hide this form from admin user %>
              <% if delivery.complete.nil? %>
                <%#= link_to 'Done', edit_delivery_path(delivery), class: 'button small' %>
                <%= form_for delivery do |f| %>
                  <%= f.hidden_field(:user_id) %>
                  <%= f.hidden_field(:customer_id) %>
                  <%= f.hidden_field(:date) %>
                  <%= f.hidden_field(:complete, value: Time.now) %>
                  <%= f.submit "Done", class: 'button small' %>
                <% end %>
              <% else %>
                <!-- Undo form -->
                <%= form_for delivery do |f| %>
                  <%= f.hidden_field(:user_id) %>
                  <%= f.hidden_field(:customer_id) %>
                  <%= f.hidden_field(:date) %>
                  <%= f.hidden_field(:complete, value: nil) %>
                  <%= f.submit "Undo", class: 'button alert small' %>
                <% end %>
                <!-- <span class="complete-time">
                  <%#= delivery.complete.strftime("%H:%M") %>
                </span> -->
              <% end %>            
            <% end %>
          </div>

        </div>
      </div>
      <div class="delivery">
        <h4><%= delivery.customer.name %></h4>
        <p><%= delivery.customer.address %></p>
        <p><strong>Travel Time:</strong>
          <% if delivery.travel_time.nil? %>
            <%= "NA" %>
          <% else %>
            <%= distance_of_time_in_words(0, delivery.travel_time) %>
          <% end %>
        </p>
        <% if current_user.admin? %>
          <p><strong>Assigned To:</strong>
            Van <%= delivery.user.van %>
             (<%= delivery.user.email %>)
          </p>
        <% end %>
      </div>
    <% end %>

app/views/layouts/_deliveries_admin.html.erb
<dl class="accordion" data-accordion>
  <% @deliveries.keys.each do |u| %>
    <dd class="accordion-navigation">
    <a class="acc-head" href="#panel<%= u.id %>"><%= u.email %></a>
    <div id="panel<%= u.id %>" class="content active">
      <table class="delivery-list">
      <colgroup>
        <col span="1" style="width: 40%;">
        <col span="1" style="width: 40%;">
        <col span="1" style="width: 40%;">
      </colgroup>
      <thead>
        <th>Customer</th><th>Status</th><th>Travel Time</th>
      </thead>
      <% @deliveries[u].each do |d| %>
        <tr>
        <td><%= link_to d.customer.name, customer_path(d.customer) %></td>
        <% if d.complete.nil? %>
          <% if d.precedence.nil? || d.precedence <= 0 %>
            <td>NA</td>
            <td>Pending</td>
          <% elsif d.precedence == 1 %>
            <td>On Route</td>  
            <td><%= distance_of_time_in_words(0, d.travel_time) %></td>                    
          <% else %>
            <td>Drop #<%= d.precedence %></td>
            <td><%= distance_of_time_in_words(0, d.travel_time) %></td>            
          <% end %>
        <% else %>
          <td>Completed @ <%= d.complete.strftime('%H:%M') %></td>
          <td>&nbsp;</td>
        <% end %>
        </tr>
      <% end %>
      </table>
    </div>
    </dd>
<% end %>
</dl>

app/views/layouts/_loading.html.erb
<div id="loading-modal" class="hide">
  <div id="tint-overlay"></div>
  <div id="loader-box" class="text-center">
    <%= image_tag('loader.gif', alt: 'Loading...') %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div data-alert class="alert-box notice">
    <%= notice %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if alert %>
  <div data-alert class="alert-box alert">
    <%= alert %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar data-options="is_hover: false">

	<ul class="title-area">
		<!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
		<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	</ul>

	<section class="top-bar-section">
		<!-- Left Nav Section -->
    <ul class="left">
      <li class="has-dropdown">
      	<a href="#">Map</a>
        <ul class="dropdown" id="nav-user-list">
          <li><a href="#" id="user-all">All</a></li>
          <%# get the user list and make menu %>
          <% nav_users.each do |u| %>
            <li><a href="#" id="user-<%= u.id %>" 
                data-user-id="<%= u.id %>"  
                data-van-id="<%= u.van %>">Van <%= u.van %></a></li>
          <% end %>
        </ul>
      </li>
      <li><%= link_to 'Deliveries', deliveries_path %></li>
      <li><%= link_to 'Customers', customers_path %></li>
      <li><%= link_to 'Upload', upload_path %></li>
    </ul>
		<!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#">Admin</a>
        <ul class="dropdown">
          <li><%= link_to 'Manage Users', users_path %></li>
          <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
        </ul>
      </li>
    </ul>
	</section>
</nav>

app/views/layouts/_navmobile.html.erb
<div class="icon-bar four-up">
  <a class="item" href="<%= root_path %>">
    <i class="fi-map"></i>
  </a>
  <a class="item" href="<%= deliveries_path %>">
    <i class="fi-clipboard-notes"></i>
  </a>
  <a class="item" href="<%= deliveries_calc_path %>">
    <i class="fi-refresh"></i>
  </a>
  <a class="item" data-method="delete" href="<%= destroy_user_session_path %>" id="item" rel="nofollow">
    <i class="fi-x-circle"></i>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= @title || Rails.application.config.deliveries[:company_name] %></title>

    <%= stylesheet_link_tag "application", media: 'all' %>
    <%# Foundation needs modernizr %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%# Bing Maps JavaScript API - need "s=1" param on url so uses SSL on Heroku %>
    <%= javascript_include_tag "https://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0&s=1" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>
  </head>

  <body>

    <%# render the correct navbar for the user %>

    <% if user_signed_in? %>
      <% if current_user.admin %>
        <%= render partial: "layouts/navbar", locals: { nav_users: @nav_users } %>
      <% else %>
        <%= render "layouts/navmobile" %>
      <% end %>
    <% end %>

    <%= render "layouts/messages" %>
    <%= render "layouts/loading" %>

    <%= yield %>

  </body>
</html>